#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m'

make || exit 1

for day in day*; do
    [ ! -f "$day"/input.txt ] && continue

    for part in "$day"/part*.c; do
        exe="${part%.c}"
        solution="$exe".solution.txt

        [ ! -f "$solution" ] && continue

        if cmp -s "$solution" <("$exe" < "$day"/input.txt | tail -1); then
            printf "%s\t${GREEN}OK${RESET}\n" "$exe"
        else
            printf "%s\t${RED}FAIL${RESET}\n" "$exe"
            failed=true
        fi
    done
done

[ -n "$failed" ] && exit 1 || exit 0
