#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m'

make || exit 1
cargo build --release || exit 1

for day in day*; do
    [ ! -f "$day"/input.txt ] && continue

    for solution in "$day"/part*.solution.txt; do
        test="${solution%.solution.txt}"

        if [ -f "$(dirname "$solution")"/Cargo.toml ]; then
            exe=./target/release/"$(basename "$(dirname "$test")")"
            args="$(basename "$test")"
        else
            exe="$test"
            args=''
        fi

        # shellcheck disable=2086
        if cmp -s "$solution" <("$exe" $args < "$day"/input.txt | tail -1); then
            printf "%s\t${GREEN}OK${RESET}\n" "$test"
        else
            printf "%s\t${RED}FAIL${RESET}\n" "$test"
            failed=true
        fi
    done
done

[ -n "$failed" ] && exit 1 || exit 0
